dist: bionic

language: python

python:
  #- "3.7"
  - "3.8"

cache:
  pip: true
  directories:
    - $HOME/db/
    - ${TRAVIS_BUILD_DIR}/scripts/output/

git:
  depth: 3

env:
  global:
    - secure: "RWSYZhUgjpL/m2qGFXwQdRztK+HHlXKV2km5mcjdIy3pALinnopVr1QpB+R/OmNEmDpx5eGUrRehseCDR6zXMx9ReLCgGmzkZGT2n6jqc9yUyR2q4AoPpljGTAWvuroBPus8v+bRhS4YzaiPrpUeFNksxKf8QJcJHL9yBD61XRLyW/WKxfCF1WCPv5PYjdVJSerqIuk9EET4ZIA73gtH1aKtTLTqXUzg+ZrVXHlP3BAtWJvd5J1+oF6/GjAY1iq5ulAxhDDeqGLjR0y1ODKSppUEC/Keisc+OyuS1HmDK7sfafzXsr6bBuZHi4yCRkTv9Yl9aQb8ulUaymBse5Ton02Q/tBy9fDuCM6/PgtDOYvjAxsI1UJWXcRgHuOsO1QUM/LdOG1pigTgWJdagzKg5JuDtnXtjfjtz36FFDxkDsbfP9BhIYxFZlvDGV1FhOpjWXYBnZJy3VcXWvSL7VacJ/hBIOhpo3OqImLnI++9a902NX/IdrWVjft7SgzIqyR18m9SzSW9PR+M0lW7q6F6pZuGp+lbl3231HMdlQFiu1AKqRqIDhJEket92BUqj7iYAlZUrQqAJQggAyLs8L/qIOl390D0dlni6xXc41p61m6sM/IFduCjGaSd3/XQJSAR+HR84CNxIKt8QlZRF/z3/Vqskx8FhHTdI9gR+cRdmEg="
    - GIT_NAME: Spirillen
    - GIT_EMAIL: "44526987+spirillen@users.noreply.github.com"
    - TRAVIS_REPO_SLUG: dns-test/rpz.mypdns.cloud
    - TZ: Europe/Berlin
    - script_dir="${TRAVIS_BUILD_DIR}/scripts"
    - testdir="${TRAVIS_BUILD_DIR}/test_data"
    - testfile="${testdir}/rpz.mypdns.cloud.list"
    - whitelist="${testdir}/whitelist.txt"
    - tag=$(date '+%F %X %Z %z')

addons:
  mariadb: '10.4'
  apt:
    packages:
      - dos2unix
      - msttcorefonts
      - lsof
      - pdns-recursor
    update: true
  
install:
  - pip3 install --upgrade pip
  - pip3 install pyfunceble-dev==2.53.6
  #- pip3 install git+https://github.com/funilrys/PyFunceble.git@dev
  #- pip3 install ultimate-hosts-blacklist-whitelist

git:
  depth: 2

matrix:
  fast_finish: true

sudo: required

script:
  # We put both in same statement so that if one fails the whole test result will fail.
  #- echo "CPU's" && lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('
  - sudo systemctl restart mysql.service pdns-recursor.service
  #- sudo mysql -u root -h localhost -e "CREATE DATABASE pyfunceble DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'pyfunceble'@'localhost' IDENTIFIED BY 'pyfunceble';"
  #- sudo mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON pyfunceble.* TO 'pyfunceble'@'localhost';"
  #- sudo mysql --user=pyfunceble --password=pyfunceble pyfunceble < ${HOME}/db/pyfunceble.sql
  #- bash scripts/test.sh && bash scripts/pyfunceble.sh && sudo mkdir -p ${HOME}/db/ && sudo mysqldump --user=pyfunceble --password=pyfunceble --opt pyfunceble > ${HOME}/db/pyfunceble.sql
  - bash scripts/test.sh && bash scripts/pyfunceble.sh && sudo mysqldump --user=pyfunceble --password=pyfunceble --opt pyfunceble > ${HOME}/db/pyfunceble.sql
