os: linux
dist: focal
language: python

python:
  #- "3.7"
  - "3.8.5"

cache:
  pip: true
  directories:
    - $HOME/db/
    - ${TRAVIS_BUILD_DIR}/scripts/output/

git:
  depth: 3

env:
  global:
    - GIT_NAME: Spirillen
    - GIT_EMAIL: "44526987+spirillen@users.noreply.github.com"
    - TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG} #dns-test/rpz.mypdns.cloud
    - TZ: UTC #Europe/Berlin
    - PYFUNCEBLE_AUTO_CONFIGURATION: YES
    #- script_dir: "${TRAVIS_BUILD_DIR}/scripts"
    #- testdir: "${TRAVIS_BUILD_DIR}/test_data"
    #- testfile: "${testdir}/rpz.mypdns.cloud.list"
    #- whitelist: "${testdir}/whitelist.txt"
    #- tag: $(date '+%F %X %Z %z')
    - Pyfunceble_version: 'PyFunceble-dev'
    - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_AUTO_CONFIGURATION: true
    - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
    - PYFUNCEBLE_DB_HOST="${DB_HOST}"
    - PYFUNCEBLE_DB_NAME="${DB_NAME}"
    - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
    - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
    - PYFUNCEBLE_DB_PORT="${DB_PORT}"

addons:
  sources:
    - sourceline: 'ppa:git-core/ppa'
    - sourceline: 'deb [arch=amd64] http://repo.powerdns.com/ubuntu focal-rec-master main'
      key_url: 'https://repo.powerdns.com/CBC8B383-pub.asc'
  #mariadb: '10.5'
  apt:
    packages:
      - dos2unix
      - msttcorefonts
      - lsof
      - pdns-recursor
      - ldnsutils
  update: true
  
install:
  - pip3 install --upgrade pip
  - pip3 install --no-cache-dir -U ${Pyfunceble_version} #"git+https://github.com/funilrys/${Pyfunceble_version}"
  #- pip3 install git+https://github.com/funilrys/PyFunceble.git@dev
  #- pip3 install ultimate-hosts-blacklist-whitelist

git:
  depth: 2

matrix:
  fast_finish: true

sudo: required

script:
  # We put both in same statement so that if one fails the whole test result will fail.
  #- echo "CPU's" && lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('
  #- sudo systemctl restart mariadb.service pdns-recursor.service
  #- sudo mysql -u root -h localhost -e "CREATE DATABASE pyfunceble DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'pyfunceble'@'localhost' IDENTIFIED BY 'pyfunceble';"
  #- sudo mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON pyfunceble.* TO 'pyfunceble'@'localhost';"
  #- sudo mysql --user=pyfunceble --password=pyfunceble pyfunceble < ${HOME}/db/pyfunceble.sql
  #- bash scripts/test.sh && bash scripts/pyfunceble.sh && sudo mkdir -p ${HOME}/db/ && sudo mysqldump --user=pyfunceble --password=pyfunceble --opt pyfunceble > ${HOME}/db/pyfunceble.sql
  - bash scripts/test.sh && bash scripts/pyfunceble.sh # && sudo mariadb-dump --host "${DB_HOST}" --user="${DB_USERNAME}" --password="${DB_PASSWORD}" --opt "${DB_NAME}" > ${HOME}/db/pyfunceble.sql
