git:
  depth: 3

env:
  global:
    - GIT_NAME: Spirillen
    - GIT_EMAIL: "44526987+spirillen@users.noreply.github.com"
    - TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG} #dns-test/rpz.mypdns.cloud
    - TZ: Europe/Berlin
    - PYFUNCEBLE_AUTO_CONFIGURATION: YES
    - Pyfunceble_version: 'PyFunceble-dev'
    - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_AUTO_CONFIGURATION: true
    - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
    - PYFUNCEBLE_DB_HOST="${DB_HOST}"
    - PYFUNCEBLE_DB_NAME="${DB_NAME}"
    - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
    - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
    - PYFUNCEBLE_DB_PORT="${DB_PORT}"

addons:
  sources:
    - sourceline: 'ppa:git-core/ppa'
    - sourceline: 'deb [arch=amd64] http://repo.powerdns.com/ubuntu focal-rec-master main'
      key_url: 'https://repo.powerdns.com/CBC8B383-pub.asc'
  apt:
    packages:
      - dos2unix
      - msttcorefonts
      - lsof
      - pdns-recursor
      - ldnsutils
  update: true
  
install:
  - pip3 install --upgrade pip
  - pip3 install --no-cache-dir -U ${Pyfunceble_version} #"git+https://github.com/funilrys/${Pyfunceble_version}"
  #- pip3 install git+https://github.com/funilrys/PyFunceble.git@dev
  #- pip3 install ultimate-hosts-blacklist-whitelist

git:
  depth: 2

jobs:
  include:
    - stage: "DNS Tests"
      language: generic
      os: linux
      dist: focal
      name: "DNS tester 1 for https://www.mypdns.org"
      script:
        - bash scripts/test.sh && bash scripts/pyfunceble.sh
    - language: generic
      os: linux
      dist: focal
      name: "DNS tester 2 for https://www.mypdns.org"
      script:
        - bash scripts/test.sh && bash scripts/pyfunceble.sh
    - language: generic
      os: linux
      dist: focal
      name: "DNS tester 3 for https://www.mypdns.org"
      script:
        - bash scripts/test.sh && bash scripts/pyfunceble.sh
    - language: generic
      os: linux
      dist: focal
      name: "DNS tester 4 for https://www.mypdns.org"
      script:
        - bash scripts/test.sh && bash scripts/pyfunceble.sh
    - language: generic
      os: linux
      dist: focal
      name: "DNS tester 5 for https://www.mypdns.org"
      script:
        - bash scripts/test.sh && bash scripts/pyfunceble.sh
